[pytest]
testpaths = tests
addopts = -v --tracing=retain-on-failure --screenshot=only-on-failure --video=retain-on-failure --cov=server --cov=pages --cov-report=term-missing --cov-report=html:reports/coverage-py
timeout = 3
